<a href="https://colab.research.google.com/github/prattayabsmrstu/skill_morph/blob/homework/Assignment_3_NumPy_and_Pandas_for_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
"""
Student Performance Dataset Analysis
Dataset Information
Student Performance Dataset (StudentsPerformance.csv)

1000 students with academic performance data
8 columns: gender, race/ethnicity, parental level of education, lunch, test preparation course, math score, reading score, writing score
Score Range: 0-100 for each subject
Demographics: Male/Female, 5 ethnic groups, 6 education levels, standard/free lunch, test prep completed/none
"""

'\nStudent Performance Dataset Analysis\nDataset Information\nStudent Performance Dataset (StudentsPerformance.csv)\n\n1000 students with academic performance data\n8 columns: gender, race/ethnicity, parental level of education, lunch, test preparation course, math score, reading score, writing score\nScore Range: 0-100 for each subject\nDemographics: Male/Female, 5 ethnic groups, 6 education levels, standard/free lunch, test prep completed/none\n'

In [12]:
#Task 1.1: Data Loading and Exploration
import numpy as np
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
file_path='/content/drive/My Drive/Colab Notebooks/StudentsPerformance.csv'
df = pd.read_csv(file_path)
# Load the dataset
#df = pd.read_csv('StudentsPerformance.csv')
# Your tasks:
# 1. Display first 10 rows
# 2. Show dataset shape and info()
# 3. Display unique values in each categorical column
# 4. Show basic statistics for all score columns

# Your code here:
df.head(10)
df.shape
df.info()
df.nunique()
df.describe()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [13]:
df.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50

In [14]:
df.shape

(1000, 8)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [16]:
df.nunique()

gender                          2
race/ethnicity                  5
parental level of education     6
lunch                           2
test preparation course         2
math score                     81
reading score                  72
writing score                  77
dtype: int64

In [17]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [18]:
#Task 1.2: NumPy Array Operations
# Convert score columns to numpy arrays
math_scores = df['math score'].values
reading_scores = df['reading score'].values
writing_scores = df['writing score'].values

# Your tasks:
# 1. Calculate mean, median, std, min, max for each subject using NumPy
# 2. Find total students who scored above 80 in math
# 3. Find total students who scored below 50 in any subject
# 4. Calculate the overall average score across all three subjects

# Expected output example:
# Math - Mean: 66.1, Median: 66.0, Std: 15.2
# Students with math > 80: 132
# Students with any score < 50: 178

# Your code here:

In [19]:
# Task 2.1: Identify and Handle Missing Data
# Check the dataset for any missing values
# Your tasks:
# 1. Check for null values in each column using .isnull().sum()
# 2. Check for any impossible values (scores > 100 or < 0)
# 3. Display summary of data quality

# Note: This dataset is clean, but let's verify!

# Your code here:
#1
df[df.isnull()]

#2
invalid_scores = df[
    (df['math score'] > 100) | (df['math score'] < 0) |
    (df['reading score'] > 100) | (df['reading score'] < 0) |
    (df['writing score'] > 100) | (df['writing score'] < 0)
]
# Display the rows with impossible values
print(f"Total invalid rows:", len(invalid_scores))

#3
summary = {
    "Total Rows": df.shape[0],
    "Total Columns": df.shape[1],
    "Missing Values": df.isnull().sum().sum(),
    "Duplicate Rows": df.duplicated().sum(),
    "Math Score Range": (df['math score'].min(), df['math score'].max()),
    "Reading Score Range": (df['reading score'].min(), df['reading score'].max()),
    "Writing Score Range": (df['writing score'].min(), df['writing score'].max()),
    "Invalid Scores": df[
        (df['math score'] < 0) | (df['math score'] > 100) |
        (df['reading score'] < 0) | (df['reading score'] > 100) |
        (df['writing score'] < 0) | (df['writing score'] > 100)
    ].shape[0]
}
print(summary)

Total invalid rows: 0
{'Total Rows': 1000, 'Total Columns': 8, 'Missing Values': np.int64(0), 'Duplicate Rows': np.int64(0), 'Math Score Range': (0, 100), 'Reading Score Range': (17, 100), 'Writing Score Range': (10, 100), 'Invalid Scores': 0}

In [20]:
#Task 2.2: Create and Fix Missing Value
# Artificially create missing data for practice
import numpy as np

# Your tasks:
# 1. Make a copy of the dataset: df_practice = df.copy()
# 2. Randomly set 50 math scores to np.nan
# 3. Randomly set 30 writing scores to np.nan
# 4. Fill missing math scores with the MEDIAN math score
# 5. Fill missing writing scores with the MEAN writing score
# 6. Verify no missing values remain

# Steps to follow:
# Step 1: Create copy and show original missing values
df_practice = df.copy()
print("Original missing values:", df_practice.isnull().sum())

# Step 2: Create missing data
np.random.seed(42)  # For reproducible results
missing_math_idx = np.random.choice(df_practice.index, 50, replace=False)
missing_writing_idx = np.random.choice(df_practice.index, 30, replace=False)

# Continue the task...
# Your code here:

Original missing values: gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [21]:
#Task 3.1:Answer Simple Questions About Student Performance
# Your tasks:
# 1. Display first 5 rows using .head()
# 2. Display last 5 rows using .tail()
# 3. Show dataset shape using .shape
# 4. Show column names using .columns
# 5. Show data types using .dtypes
# 6. Show basic info using .info()df.info()

# Your code here:
df.head(5)
df.tail(5)
df.shape
df.columns
df.dtypes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [22]:
#Task 3.2: Basic Groupby Analysis
# Comprehensive groupby analysis
# Your tasks:

# 1. Group by 'gender' and calculate:
#    - Average scores in all subjects
#    - Count of students

# 2. Group by 'test preparation course' and show:
#    - Mean scores for each subject
#    - Show which subject benefits most from test prep

# 3. Group by 'parental level of education' and calculate:
#    - Average math score for each education level
#    - Rank education levels by math performance

# 4. Group by 'lunch' type and show:
#    - Average scores for each subject
#    - Count of students in each lunch category

# Your code here:
#task 1
avg_scores = df.groupby('gender')[['math score', 'reading score', 'writing score']].mean()
print(avg_scores)

student_counts = df['gender'].value_counts()
print(student_counts)

#task 2
prep_scores = df.groupby('test preparation course')[['math score', 'reading score', 'writing score']].mean()
score_diff = prep_scores.loc['completed'] - prep_scores.loc['none']
most_improved_subject = score_diff.idxmax()

print(" Mean Scores by Test Preparation Course:")
print(prep_scores)

print("\n Score Improvements from Test Prep:")
print(score_diff)

print(f"\n Subject that benefits most from test prep: {most_improved_subject}")

#3
math_by_education = df.groupby('parental level of education')['math score'].mean()
ranked_math = math_by_education.sort_values(ascending=False)

# Display results
print("Average Math Score by Parental Education Level:")
print(math_by_education)

print("\n Ranked Education Levels by Math Performance:")
print(ranked_math)

#4
# Group by lunch type and calculate average scores
avg_scores_by_lunch = df.groupby('lunch')[['math score', 'reading score', 'writing score']].mean()

# Count of students in each lunch category
student_count_by_lunch = df['lunch'].value_counts()

# Display results
print("Average Scores by Lunch Type:")
print(avg_scores_by_lunch)

print("\nStudent Count by Lunch Type:")
print(student_count_by_lunch)

        math score  reading score  writing score
gender
female   63.633205      72.608108      72.467181
male     68.728216      65.473029      63.311203
gender
female    518
male      482
Name: count, dtype: int64
 Mean Scores by Test Preparation Course:
                         math score  reading score  writing score
test preparation course
completed                 69.695531      73.893855      74.418994
none                      64.077882      66.534268      64.504673

 Score Improvements from Test Prep:
math score       5.617649
reading score    7.359587
writing score    9.914322
dtype: float64

 Subject that benefits most from test prep: writing score
Average Math Score by Parental Education Level:
parental level of education
associate's degree    67.882883
bachelor's degree     69.389831
high school           62.137755
master's degree       69.745763
some college          67.128319
some high school      63.497207
Name: math score, dtype: float64

 Ranked Education Levels by Math Performance:
parental level of education
master's degree       69.745763
bachelor's degree     69.389831
associate's degree    67.882883
some college          67.128319
some high school      63.497207
high school           62.137755
Name: math score, dtype: float64
Average Scores by Lunch Type:
              math score  reading score  writing score
lunch
free/reduced   58.921127      64.653521      63.022535
standard       70.034109      71.654264      70.823256

Student Count by Lunch Type:
lunch
standard        645
free/reduced    355
Name: count, dtype: int64

In [23]:
#Task 3.3: Use your data analysis skills to answer these easy questions:

# 1. Who performs better in math - males or females?
#    - Calculate average math score by gender
#    - Show the difference between male and female average

# 2. Which subject do students perform best in overall?
#    - Calculate the overall average for math, reading, and writing
#    - Rank the subjects from highest to lowest average score

# 3. What's the impact of parental education?
#    - Find the average total score for each parental education level
#    - Identify which education level leads to highest student performance